In [4]:
x = 3

In [3]:
from datascience import *
import numpy as np
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update(
    "livereveal", {
        "width": "90%",
        "height": "90%",
        "scroll": True,
})

{'width': '90%', 'height': '90%', 'scroll': True}

# Hi everyone, welcome to DSC 10!
---

This discussion section is meant to cover some of the basics of Python that you've seen so far in this class.

If at any point you have a question, feel free to ask—just don't interrupt in the middle of a sentence :)

# What we'll cover tonight:
---

- What is Python?
- Data Types
- Variables
- Functions
- Creating a Table

# What is Python?
---

Python is a **high-level**, **interpreted** programming language invented by Guido Van Rossum in 1991.  It is a powerful language while remaining **dynamically-typed**, easily **readable**, and has plenty of **whitespace**.

- High-level:
  - Don't need to worry about giving instructions to the computer

- Interpreted:
  - A file or cell can run instantly; does not need to compile another file

- Dynamically Typed:
  - Python infers what type you want a variable to be; you don't tell it explicitly

- Readable:
  - Simply reading code aloud should largely reveal what's going on

- Whitespace:
  - You can *and should* use multiple lines to make fit the `Python  a e s t h e t i c`

# Data Types in Python
---

Everything in Python has a type.

Some things are really simple—you could call them *"primitive"*.  
These things have a specific value.

There are four types of primitives:
- Integers
- Floats
- Strings
- Booleans

Other things are a bit more complex.  
These things act more like containers for values (or more containers).

Some examples include:
- Lists
- Arrays
- Tables

### Primitive Types: integers, floats, strings, booleans

In [5]:
# Integers
type(65)

int

In [3]:
# Floats
type(1.08765)

float

In [4]:
# Strings
type("Hello")
type("'World'")

str

In [6]:
# Booleans (True or False)
type(False)

bool

What are some things we can do with these primitive types?

In [7]:
# Let's do some testing together... here's a couple to start with:

3 + 5 # Can we do this?

8

In [10]:
3 + 5.9876 # What about this?

8.9876

### Some Others: lists, arrays, and tables

In [15]:
# Lists
type([[5,2,'hello'], '1', 2, '3']) # Lists can contain any type of data
['hi', ['how', 'are', 'you']]

['hi', ['how', 'are', 'you']]

In [19]:
l = [1, 2, 3] # I want to add 4 to this list
# We can use np.append to do this!
l
l = np.append(l, 4)
l

array([1, 2, 3, 4])

In [20]:
# NumPy Arrays
import numpy as np

# NumPy Arrays will fit all data to **the same type**
type(np.array([1, 2, 3]))

numpy.ndarray

In [21]:
# We need to import datascience first
from datascience import *

type(make_array(1, 2, 3)) # This is the same as before!
#! IMPORTANT:  np.array takes a LIST, but make_array takes INDIVIDUAL VALUES

numpy.ndarray

In [22]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [26]:
make_array(True, [1])

ValueError: setting an array element with a sequence.

In [23]:
np.array([1, 2, 'a string'])

array(['1', '2', 'a string'], dtype='<U21')

In [ ]:
# Can we add a value to an array too?

In [31]:
str([1,4,3,2])

'[1, 4, 3, 2]'

In [27]:
# And tables... as we'll see in a moment
from datascience import *
type(Table())

datascience.tables.Table

Recap:

All objects in Python have a type, some of which are primitive, some of which act more like containers.

If we ever forget what type something is, we can use `type()` to find out!

# Variables
---

In Python when you assign a variable like this:

`x = 4`

You're essentially telling Python this:

`From now on, please let the value of 'x' be assigned to the value of 4.`

In [32]:
x = 4
y = "Why"
z = [4.0, "That's the dream..."]
class_choice = make_array("Cake", 3.14)

print(x)
print(y)
print(z)
print(class_choice)

4
Why
[4.0, "That's the dream..."]
['Cake' '3.14']


What happens if we assign x again?

In [33]:
print(x)

4


In [35]:
x = "6"
print(x)

6


Recall that variables assume the type of what you assign it to

In [36]:
print(type(x))
print(type(y))
print(type(z))
print(type(class_choice))

<class 'str'>
<class 'str'>
<class 'list'>
<class 'numpy.ndarray'>


We can even assign variables to other variables, but it can get a bit tricky.

In [37]:
x = 1
y = x
x = 2

print("y == x?       ", y == x)

y == x?        False


In [39]:
x = None

Wait but I thought we just set `y = x`!

Recall that we're telling Python to assign y **to the value of** x, not directly to x!

What is the value of something then?
It's whatever is returned if you run it at the end of a cell.

In [41]:
# The value of x is
x
q

NameError: name 'q' is not defined

# Functions
---

Functions, like `print()`, allow us to easily run something with different parameters.

We can also define our own functions to allow us to run our own code multiple times with different parameters.

Most functions take values as inputs.  
Most functions will return a value.  

Just like all values in Python, these have a type!

So, it's important that we know what a function takes and what it returns.

This helps alot when it comes to fixing bad code!

In [42]:
help(Table.column)

Help on function column in module datascience.tables:

column(self, index_or_label)
    Return the values of a column as an array.
    
    table.column(label) is equivalent to table[label].
    
    >>> tiles = Table().with_columns(
    ...     'letter', make_array('c', 'd'),
    ...     'count',  make_array(2, 4),
    ... )
    
    >>> list(tiles.column('letter'))
    ['c', 'd']
    >>> tiles.column(1)
    array([2, 4])
    
    Args:
        label (int or str): The index or label of a column
    
    Returns:
        An instance of ``numpy.array``.
    
    Raises:
        ``ValueError``: When the ``index_or_label`` is not in the table.



A Python function is called with the following format:

`function_name(parameter_1, parameter_2, ...)`

For example, `sum` takes a list (or array-like object) as a parameter.  
The function `len` can take a list too.

In [45]:
sum ( np.array([1, 2, 3]) )

6

In [44]:
len(np.array([1, 2, 3, 4]))

4

And other functions, like `pow` take more than one argument.

In [46]:
help(pow)

Help on built-in function pow in module builtins:

pow(x, y, z=None, /)
    Equivalent to x**y (with two arguments) or x**y % z (with three arguments)
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [47]:
pow(1.618, 2)

2.6179240000000004

Some objects have their own functions!  
To call this, you need to use "dot notation", it looks like this:


`some_object.func_name(parameter_1, ...)`

In [49]:
tbl = Table()

tbl.with_column("Hello", ["wow", "that's", "cool"]).with_column("Goodbye", ":(")

Hello  | Goodbye
wow    | :(
that's | :(
cool   | :(

We can assign a variable to the result of a function the same way we assign any variable!

In [52]:
x = print("hih")
x + 5

hih


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

We define our own functions with the following general format:

```
def func_name(parameter_1, parameter_2, ...):
    
    # Do something useful
    result = ...

    return result
```

Let's create our own function that multiplies two numbers and gives us back the result.

In [55]:
class_example(5, 8.8)

44.0

In [54]:
# Write some code together :)
def class_example(num1, num2):
    
    return num1 * num2

# Some Work With Tables
---

Tables are a handy way to store a bunch of related data.

Let's create our own table using the *datascience package* and play around with it a bit.

As we saw before, we can create a new, empty table by calling Table(). 

In [59]:
# We should probably assign this to a variable
# if we want to do anything interesting with it!
tbl = Table()
tbl

There are many ways to fill in a table, such as by adding rows or importing from a csv.

Adding columns is a simple way, so let's do that!

We can call the function `with_column` on a Table object.  
Then pass in the parameters: `column_name, [data]`

The values in a column of a table should have **the same type**, so it makes sense to use np.array where possible!

In [60]:
tbl.with_column("interesting numbers", np.arange(5))

interesting numbers
0
1
2
3
4

In [61]:
tbl

Don't forget to reassign to the variable, or your changes will **not** be saved!

In [66]:
tbl = tbl.with_column("interesting numbers", np.arange(5))
tbl
# Let's add some more columns together.

interesting numbers
0
1
2
3
4

In [64]:
tbl = tbl.drop("interesting numbers")
tbl

In [68]:
tbl = tbl.sort("interesting numbers")
tbl

interesting numbers
0
1
2
3
4

We can get a column of data by calling `column` on the table object.  
Then pass in the parameter `column_name`; the name of the column you want.

In [69]:
help(Table.column)

Help on function column in module datascience.tables:

column(self, index_or_label)
    Return the values of a column as an array.
    
    table.column(label) is equivalent to table[label].
    
    >>> tiles = Table().with_columns(
    ...     'letter', make_array('c', 'd'),
    ...     'count',  make_array(2, 4),
    ... )
    
    >>> list(tiles.column('letter'))
    ['c', 'd']
    >>> tiles.column(1)
    array([2, 4])
    
    Args:
        label (int or str): The index or label of a column
    
    Returns:
        An instance of ``numpy.array``.
    
    Raises:
        ``ValueError``: When the ``index_or_label`` is not in the table.



In [70]:
tbl.column("interesting numbers")

array([0, 1, 2, 3, 4])

Notice the data type that is returned!

This means it's easy for us to do calculations immediately after grabbing the columns.

In [77]:
from math import factorial as f
f(0)

1

In [73]:
# Let's do some calculations here
print(tbl.column(0))
print(np.arange(5))
# tbl.column(0) ** np.arange(5)

[0 1 2 3 4]
[0 1 2 3 4]


Questions? Let's try them right now!

In [85]:
tbl = Table(["Number", "Word"]).with_rows(
make_array(
    make_array(1, "Two"),
    make_array(3, "Four")
)
)
tbl

Number | Word
1      | Two
3      | Four

In [89]:
Table(["Name"]).with_row([1])

Name
1

In [92]:
Table('Name')

N    | a    | m    | e

In [87]:
Table().with_columns(
    "Name", make_array()
)
Table("Name").with_row(make_array("value"))

Exception: Row should have 4 columns

In [81]:
help(Table.with_rows)

Help on function with_rows in module datascience.tables:

with_rows(self, rows)
    Return a table with additional rows.
    
    Args:
        ``rows`` (sequence of sequences): Each row has a value per column.
    
        If ``rows`` is a 2-d array, its shape must be (_, n) for n columns.
    
    Raises:
        ``ValueError``: If a row length differs from the column count.
    
    >>> tiles = Table(make_array('letter', 'count', 'points'))
    >>> tiles.with_rows(make_array(make_array('c', 2, 3),
    ...     make_array('d', 4, 2)))
    letter | count | points
    c      | 2     | 3
    d      | 4     | 2

